export type NutritionInterface = {
    nutrition_id: number,
    ingredient_name: number,
    weight:number,
    energy: number,
    protein: number,
    total_fat:number,
    saturated_fat:number,
    trans_fat:number,
    polysat_fat:number,
    monosat_fat:number,
    carb:number,
    sugar:number,
    added_sugar:number,
    free_sugar:number,
    dietery_fibre:number,
    thiamin:number,
    riboflarin:number,
    niacin:number,
    vitamin_c:number,
    vitamin_e:number,
    vitamin_b6:number,
    vitamin_b12:number,
    total_folate:number,
    total_vitamin_a:number,
    sodium:number,
    potassium:number,
    magnessium:number,
    calcium:number,
    phosphorus:number,
    iron:number,
    zinc:number,
    selenium:number,
    iodine:number,
    omega3:number,
    protien_foods:number
  };

  export interface RequestNutritionInterface{
    ingredient_name: string,
    weight:number,
    energy: number,
    protein: number,
    total_fat:number,
    saturated_fat:number,
    trans_fat:number,
    polysat_fat:number,
    monosat_fat:number,
    carb:number,
    sugar:number,
    added_sugar:number,
    free_sugar:number,
    dietery_fibre:number,
    thiamin:number,
    riboflarin:number,
    niacin:number,
    vitamin_c:number,
    vitamin_e:number,
    vitamin_b6:number,
    vitamin_b12:number,
    total_folate:number,
    total_vitamin_a:number,
    sodium:number,
    potassium:number,
    magnessium:number,
    calcium:number,
    phosphorus:number,
    iron:number,
    zinc:number,
    selenium:number,
    iodine:number,
    omega3:number,
    protien_foods:number

  }